version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "isak-resume-sam-bucket"
s3_prefix = "sam-app"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"